@startuml

' !include <C4/C4_Component>

class Empresa {
    codigo: varchar(10)
    nombre: varchar(255)
}

class Cuadro {
    aprobada: integer(10)
    cubierta: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "1" Cuadro

class CargoSinCubrir {
    cargo: varchar(255)
    cuadro_id:integer(10)
}
Cuadro "1" -- "*" CargoSinCubrir

class AtencionPoblacion {
    quejas: integer(10)
    peticiones: integer(10)
    termino: varchar(10)
    empresa_id: integer(10)
}
Empresa "1" -- "1" AtencionPoblacion

class CapitalHumano {
    plantillaAprobada: integer(10)
    plantillaCubierta: integer(10)
    mujeres: integer(10)
    empresa_id: integer(10)
}

Empresa "1" -- "1" CapitalHumano


class Interruptos {
    total: integer(10)
    equiposRotos: integer(10)
    faltaPiezas: integer(10)
    otrasCausas: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "1" Interruptos

class Delitos {
    denuncia: integer(10)
    municipio: varchar(50)
    fecha: date()
    unidad: varchar(50)
    tipocidad: varchar(50)
    productosSustraidos: varchar(255)
    valorPerdidas: float(2)
    medidasTomadas: varchar(50)
    empresa_id: integer(10)
}
Empresa "1" -- "*" Delitos

class PlanRecape {
    plan: integer(10)
    mes: integer(10)
    anno: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "1" PlanRecape

class PlanMateriaPrima {
    plan: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "1" PlanMateriaPrima

class TipoMateriaPrima{
    plan_materia_prima_id: integer(10)
    tipo: varchar(10)
    cantidad: integer(10)
}
PlanMateriaPrima "1"--"*" TipoMateriaPrima


class Inmuebles {
    tipo: varchar(255)
    cantidad: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "*" Inmuebles

class PlanDeMantenimiento {
    plan: integer(10)
    real: integer(10)
    porciento: integer(10)
    tipo: varchar(70)
    empresa_id: integer(10)
}
Empresa "1" -- "1" PlanDeMantenimiento

class Inversiones {
    plan: integer(10)
    real: integer(10)
    porciento: integer(10)
    tipo: varchar(70)
    Empresacodigo: varchar(10)
}
Empresa "1" -- "1" Inversiones


class IndicadorGeneral {
    plan: integer(10)
    real: integer(10)
    porciento: integer(10)
    tipo: varchar(70)
    Empresacodigo: varchar(10)
}
Empresa "1" -- "1" IndicadorGeneral

class Deficiencias {
    total: integer(10)
    resueltas: integer(10)
    pendientes: integer(10)
    empresa_id: integer(10)
}
Empresa "1" -- "*" Deficiencias


class UEBperdidas {
    cantidadUEB: integer(10)
    nombre: varchar(255)
    municipio: varchar(255)
    empresa_id: integer(10)
}
Empresa "1" -- "*" UEBperdidas

class CuentasCobrar {
    inicio_anno: float()
    mes_anterior: float()
    mes_actual: float()
    diferencia_incio_anno: float()
    diferencia_mes_anterior: float()
    saldo_al_inicio: float()
    mes_anterior_vencidas: float()
    mes_actual_vencidas: float()
    indice_gestion_cloro: float()
    ciclo_cobros_dias: float()
    empresa_id: integer(10)
}
Empresa "1" -- "1" CuentasCobrar
class CuentasPagar {
    inicio_anno: float()
    mes_anterior: float()
    mes_actual: float()
    diferencia_incio_anno: float()
    diferencia_mes_anterior: float()
    saldo_al_inicio: float()
    mes_anterior_vencidas: float()
    mes_actual_vencidas: float()
    indice_gestion_cloro: float()
    ciclo_cobros_dias: float()
    empresa_id: integer(10)
}
Empresa "1" -- "1" CuentasPagar



@enduml