# Generated by Django 4.2.7 on 2025-03-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deficiencias",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="uebperdidas",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inmuebles",
            unique_together={("tipo", "empresa")},
        ),
        migrations.AlterUniqueTogether(
            name="uebperdidas",
            unique_together={("nombre", "empresa")},
        ),
    ]
