# Generated by Django 4.2.7 on 2025-03-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0002_alter_deficiencias_empresa_alter_delitos_empresa_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atencionpoblacion",
            options={
                "verbose_name": "Atención a la Población",
                "verbose_name_plural": "Atenciones a la Población",
            },
        ),
        migrations.AlterModelOptions(
            name="capitalhumano",
            options={
                "verbose_name": "Capital Humano",
                "verbose_name_plural": "Capital Humano",
            },
        ),
        migrations.AlterModelOptions(
            name="cargosincubrir",
            options={
                "verbose_name": "Cargo sin Cubrir",
                "verbose_name_plural": "Cargos sin Cubrir",
            },
        ),
        migrations.AlterModelOptions(
            name="cuadro",
            options={
                "verbose_name": "Cuadro",
                "verbose_name_plural": "Cuadros",
            },
        ),
        migrations.AlterModelOptions(
            name="cuentascobrar",
            options={
                "verbose_name": "Cuenta por Cobrar",
                "verbose_name_plural": "Cuentas por Cobrar",
            },
        ),
        migrations.AlterModelOptions(
            name="cuentaspagar",
            options={
                "verbose_name": "Cuenta por Pagar",
                "verbose_name_plural": "Cuentas por Pagar",
            },
        ),
        migrations.AlterModelOptions(
            name="deficiencias",
            options={
                "verbose_name": "Deficiencia",
                "verbose_name_plural": "Deficiencias",
            },
        ),
        migrations.AlterModelOptions(
            name="delitos",
            options={
                "verbose_name": "Delito",
                "verbose_name_plural": "Delitos",
            },
        ),
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterModelOptions(
            name="indicadorgeneral",
            options={
                "verbose_name": "Indicador General",
                "verbose_name_plural": "Indicadores Generales",
            },
        ),
        migrations.AlterModelOptions(
            name="inmuebles",
            options={
                "verbose_name": "Inmueble",
                "verbose_name_plural": "Inmuebles",
            },
        ),
        migrations.AlterModelOptions(
            name="interruptos",
            options={
                "verbose_name": "Interrupto",
                "verbose_name_plural": "Interruptos",
            },
        ),
        migrations.AlterModelOptions(
            name="inversiones",
            options={
                "verbose_name": "Inversión",
                "verbose_name_plural": "Inversiones",
            },
        ),
        migrations.AlterModelOptions(
            name="plandemantenimiento",
            options={
                "verbose_name": "Plan de Mantenimiento",
                "verbose_name_plural": "Planes de Mantenimiento",
            },
        ),
        migrations.AlterModelOptions(
            name="planmateriaprima",
            options={
                "verbose_name": "Plan de Materia Prima",
                "verbose_name_plural": "Planes de Materia Prima",
            },
        ),
        migrations.AlterModelOptions(
            name="planrecape",
            options={
                "verbose_name": "Plan de Recape",
                "verbose_name_plural": "Planes de Recape",
            },
        ),
        migrations.AlterModelOptions(
            name="tipomateriaprima",
            options={
                "verbose_name": "Tipo de Materia Prima",
                "verbose_name_plural": "Tipos de Materia Prima",
            },
        ),
        migrations.AlterModelOptions(
            name="uebperdidas",
            options={
                "verbose_name": "UEB Pérdida",
                "verbose_name_plural": "UEB Pérdidas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="inmuebles",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="uebperdidas",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="atencionpoblacion",
            name="denuncias",
            field=models.IntegerField(default=0, verbose_name="Denuncias"),
        ),
        migrations.AlterField(
            model_name="atencionpoblacion",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="atencionpoblacion",
            name="peticiones",
            field=models.IntegerField(verbose_name="Peticiones"),
        ),
        migrations.AlterField(
            model_name="atencionpoblacion",
            name="quejas",
            field=models.IntegerField(verbose_name="Quejas"),
        ),
        migrations.AlterField(
            model_name="atencionpoblacion",
            name="termino",
            field=models.CharField(max_length=10, verbose_name="Término"),
        ),
        migrations.AlterField(
            model_name="capitalhumano",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="capitalhumano",
            name="mujeres",
            field=models.IntegerField(verbose_name="Cantidad de Mujeres"),
        ),
        migrations.AlterField(
            model_name="capitalhumano",
            name="plantillaAprobada",
            field=models.IntegerField(verbose_name="Plantilla Aprobada"),
        ),
        migrations.AlterField(
            model_name="capitalhumano",
            name="plantillaCubierta",
            field=models.IntegerField(verbose_name="Plantilla Cubierta"),
        ),
        migrations.AlterField(
            model_name="cargosincubrir",
            name="cargo",
            field=models.CharField(max_length=255, verbose_name="Cargo"),
        ),
        migrations.AlterField(
            model_name="cargosincubrir",
            name="cuadro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.cuadro",
                verbose_name="Cuadro",
            ),
        ),
        migrations.AlterField(
            model_name="cuadro",
            name="aprobada",
            field=models.IntegerField(verbose_name="Cantidad Aprobada"),
        ),
        migrations.AlterField(
            model_name="cuadro",
            name="cubierta",
            field=models.IntegerField(verbose_name="Cantidad Cubierta"),
        ),
        migrations.AlterField(
            model_name="cuadro",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="ciclo_cobros_dias",
            field=models.FloatField(verbose_name="Ciclo de Cobros (Días)"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="diferencia_incio_anno",
            field=models.FloatField(
                verbose_name="Diferencia con Inicio de Año"
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="diferencia_mes_anterior",
            field=models.FloatField(verbose_name="Diferencia con Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="indice_gestion_cloro",
            field=models.FloatField(verbose_name="Índice Gestión Cloro"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="inicio_anno",
            field=models.FloatField(verbose_name="Inicio de Año"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_actual",
            field=models.FloatField(verbose_name="Mes Actual"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_actual_vencidas",
            field=models.FloatField(verbose_name="Vencidas Mes Actual"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_anterior",
            field=models.FloatField(verbose_name="Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_anterior_vencidas",
            field=models.FloatField(verbose_name="Vencidas Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="saldo_al_inicio",
            field=models.FloatField(verbose_name="Saldo al Inicio"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="ciclo_cobros_dias",
            field=models.FloatField(verbose_name="Ciclo de Cobros (Días)"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="diferencia_incio_anno",
            field=models.FloatField(
                verbose_name="Diferencia con Inicio de Año"
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="diferencia_mes_anterior",
            field=models.FloatField(verbose_name="Diferencia con Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="indice_gestion_cloro",
            field=models.FloatField(verbose_name="Índice Gestión Cloro"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="inicio_anno",
            field=models.FloatField(verbose_name="Inicio de Año"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_actual",
            field=models.FloatField(verbose_name="Mes Actual"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_actual_vencidas",
            field=models.FloatField(verbose_name="Vencidas Mes Actual"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_anterior",
            field=models.FloatField(verbose_name="Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_anterior_vencidas",
            field=models.FloatField(verbose_name="Vencidas Mes Anterior"),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="saldo_al_inicio",
            field=models.FloatField(verbose_name="Saldo al Inicio"),
        ),
        migrations.AlterField(
            model_name="deficiencias",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="deficiencias",
            name="pendientes",
            field=models.IntegerField(verbose_name="Pendientes"),
        ),
        migrations.AlterField(
            model_name="deficiencias",
            name="resueltas",
            field=models.IntegerField(verbose_name="Resueltas"),
        ),
        migrations.AlterField(
            model_name="deficiencias",
            name="total",
            field=models.IntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="denuncia",
            field=models.IntegerField(verbose_name="Número de Denuncia"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="fecha",
            field=models.DateField(auto_now=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="medidasTomadas",
            field=models.CharField(
                max_length=50, verbose_name="Medidas Tomadas"
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="municipio",
            field=models.CharField(max_length=50, verbose_name="Municipio"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="productosSustraidos",
            field=models.CharField(
                max_length=255, verbose_name="Productos Sustraídos"
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="tipocidad",
            field=models.CharField(max_length=50, verbose_name="Tipicidad"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="unidad",
            field=models.CharField(max_length=50, verbose_name="Unidad"),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="valorPerdidas",
            field=models.FloatField(verbose_name="Valor de Pérdidas"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="codigo",
            field=models.CharField(max_length=10, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="plan",
            field=models.IntegerField(verbose_name="Plan"),
        ),
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="porciento",
            field=models.IntegerField(verbose_name="Porcentaje"),
        ),
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="real",
            field=models.IntegerField(verbose_name="Real"),
        ),
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="tipo",
            field=models.CharField(max_length=70, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="cantidad",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="tipo",
            field=models.CharField(max_length=255, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="interruptos",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="interruptos",
            name="equiposRotos",
            field=models.IntegerField(verbose_name="Equipos Rotos"),
        ),
        migrations.AlterField(
            model_name="interruptos",
            name="faltaPiezas",
            field=models.IntegerField(verbose_name="Falta de Piezas"),
        ),
        migrations.AlterField(
            model_name="interruptos",
            name="otrasCausas",
            field=models.IntegerField(verbose_name="Otras Causas"),
        ),
        migrations.AlterField(
            model_name="interruptos",
            name="total",
            field=models.IntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inversiones",
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="plan",
            field=models.IntegerField(verbose_name="Plan"),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento",
            field=models.IntegerField(verbose_name="Porcentaje"),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="real",
            field=models.IntegerField(verbose_name="Real"),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="tipo",
            field=models.CharField(max_length=70, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="plan",
            field=models.IntegerField(verbose_name="Plan"),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="porciento",
            field=models.IntegerField(verbose_name="Porcentaje"),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="real",
            field=models.IntegerField(verbose_name="Real"),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="tipo",
            field=models.CharField(max_length=70, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="planmateriaprima",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="planmateriaprima",
            name="plan",
            field=models.IntegerField(verbose_name="Plan"),
        ),
        migrations.AlterField(
            model_name="planrecape",
            name="anno",
            field=models.IntegerField(verbose_name="Año"),
        ),
        migrations.AlterField(
            model_name="planrecape",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="planrecape",
            name="mes",
            field=models.IntegerField(verbose_name="Mes"),
        ),
        migrations.AlterField(
            model_name="planrecape",
            name="plan",
            field=models.IntegerField(verbose_name="Plan"),
        ),
        migrations.AlterField(
            model_name="tipomateriaprima",
            name="cantidad",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="tipomateriaprima",
            name="plan_materia_prima",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.planmateriaprima",
                verbose_name="Plan de Materia Prima",
            ),
        ),
        migrations.AlterField(
            model_name="tipomateriaprima",
            name="tipo",
            field=models.CharField(max_length=10, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="uebperdidas",
            name="cantidadUEB",
            field=models.IntegerField(verbose_name="Cantidad de UEB"),
        ),
        migrations.AlterField(
            model_name="uebperdidas",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="uebperdidas",
            name="municipio",
            field=models.CharField(max_length=255, verbose_name="Municipio"),
        ),
        migrations.AlterField(
            model_name="uebperdidas",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
    ]
