# Generated by Django 4.2.7 on 2025-03-31 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_atencionpoblacion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delitos",
            name="no_denuncia",
            field=models.IntegerField(
                default=1,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Código",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delitos",
            name="fecha",
            field=models.DateField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="codigo",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Código"
            ),
        ),
    ]
