# Generated by Django 4.2.7 on 2025-04-01 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_planmateriaprima_empresa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planmateriaprima",
            unique_together={("anno", "empresa")},
        ),
        migrations.RemoveField(
            model_name="planmateriaprima",
            name="mes",
        ),
    ]
