# Generated by Django 4.2.7 on 2025-03-31 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_delitos_no_denuncia_alter_delitos_fecha_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="delitos",
            unique_together={("no_denuncia", "empresa")},
        ),
    ]
