# Generated by Django 4.2.7 on 2025-03-31 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_delitos_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delitos",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
    ]
