# Generated by Django 4.2.7 on 2025-03-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_delitos_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrecape",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planrecape",
            unique_together={("mes", "anno", "empresa")},
        ),
    ]
