# Generated by Django 4.2.7 on 2025-04-02 00:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0006_remove_inmuebles_cantidad_remove_inmuebles_tipo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plandemantenimiento",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="plandemantenimiento",
            name="porciento",
        ),
        migrations.RemoveField(
            model_name="plandemantenimiento",
            name="real",
        ),
        migrations.RemoveField(
            model_name="plandemantenimiento",
            name="tipo",
        ),
        migrations.AddField(
            model_name="plandemantenimiento",
            name="anno",
            field=models.IntegerField(default=2025, verbose_name="Año"),
        ),
        migrations.AddField(
            model_name="plandemantenimiento",
            name="cantidad_de_obras_anual",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad De Obras Anual"
            ),
        ),
        migrations.AddField(
            model_name="plandemantenimiento",
            name="cantidad_de_obras_real",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad De Obras Real"
            ),
        ),
        migrations.AddField(
            model_name="plandemantenimiento",
            name="importe_total_anual",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Importe Total Anual",
            ),
        ),
        migrations.AddField(
            model_name="plandemantenimiento",
            name="importe_total_real",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Importe Total Real",
            ),
        ),
        migrations.AlterField(
            model_name="plandemantenimiento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.empresa",
                verbose_name="Empresa",
            ),
        ),
    ]
