# Generated by Django 4.2.7 on 2025-04-01 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_planrecape_empresa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planmateriaprima",
            name="plan",
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="anno",
            field=models.IntegerField(default=2024, verbose_name="Año"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="mes",
            field=models.IntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                default="",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="El mes debe estar entre 1 y 12"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, message="El mes debe estar entre 1 y 12"
                    ),
                ],
                verbose_name="Mes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planrecape",
            name="mes",
            field=models.IntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="El mes debe estar entre 1 y 12"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, message="El mes debe estar entre 1 y 12"
                    ),
                ],
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="tipomateriaprima",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Papel y Cartón", "Papel y Cartón"),
                    ("Chatarra de acero", "Chatarra de acero"),
                    ("Envase Textil", "Envase Textil"),
                    ("Chatarra aluminio", "Chatarra aluminio"),
                    ("Chatarra Plomo", "Chatarra Plomo"),
                    ("Polietileno", "Polietileno"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
