# Generated by Django 4.2.7 on 2025-04-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_remove_planmateriaprima_plan_planmateriaprima_anno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planmateriaprima",
            name="chatarra_acero",
            field=models.IntegerField(default=0, verbose_name="Chatarra de acero"),
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="chatarra_aluminio",
            field=models.IntegerField(default=0, verbose_name="Chatarra aluminio"),
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="chatarra_plomo",
            field=models.IntegerField(default=0, verbose_name="Chatarra Plomo"),
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="envase_textil",
            field=models.IntegerField(default=0, verbose_name="Envase Textil"),
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="papel_carton",
            field=models.IntegerField(default=0, verbose_name="Papel y Cartón"),
        ),
        migrations.AddField(
            model_name="planmateriaprima",
            name="polietileno",
            field=models.IntegerField(default=0, verbose_name="Polietileno"),
        ),
        migrations.DeleteModel(
            name="TipoMateriaPrima",
        ),
    ]
