# Generated by Django 4.2.7 on 2025-04-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_plandemantenimiento_anno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inversiones",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="inversiones",
            name="porciento",
        ),
        migrations.RemoveField(
            model_name="inversiones",
            name="real",
        ),
        migrations.RemoveField(
            model_name="inversiones",
            name="tipo",
        ),
        migrations.AddField(
            model_name="inversiones",
            name="plan_no_nominales",
            field=models.IntegerField(
                default=0, verbose_name="Inversiones no nominales: Plan"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="plan_obra",
            field=models.IntegerField(
                default=0, verbose_name="Preparación de obra: Plan"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="plan_resto",
            field=models.IntegerField(
                default=0,
                verbose_name="Resto de inversiones no nominales: Plan",
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="porciento_no_nominales",
            field=models.IntegerField(
                default=0, verbose_name="Inversiones no nominales: Porcentaje"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="porciento_obra",
            field=models.IntegerField(
                default=0, verbose_name="Preparación de obra: Porcentaje"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="porciento_resto",
            field=models.IntegerField(
                default=0,
                verbose_name="Resto de inversiones no nominales: Porcentaje",
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="real_no_nominales",
            field=models.IntegerField(
                default=0, verbose_name="Inversiones no nominales: Real"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="real_obra",
            field=models.IntegerField(
                default=0, verbose_name="Preparación de obra: Real"
            ),
        ),
        migrations.AddField(
            model_name="inversiones",
            name="real_resto",
            field=models.IntegerField(
                default=0,
                verbose_name="Resto de inversiones no nominales: Real",
            ),
        ),
    ]
