# Generated by Django 4.2.7 on 2025-04-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_materialplasticoreciclado"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDeConstruccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=255, verbose_name="Material")),
                (
                    "unidad_de_medida",
                    models.CharField(max_length=255, verbose_name="Unidad de Medida"),
                ),
                ("plan", models.IntegerField(verbose_name="Plan")),
                ("real", models.IntegerField(verbose_name="Real")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material de Construcción",
                "verbose_name_plural": "Materiales de Construcción",
            },
        ),
    ]
