# Generated by Django 4.2.7 on 2025-04-03 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_materialdeconstruccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuentaspagar",
            name="ciclo_cobros_dias",
        ),
        migrations.RemoveField(
            model_name="cuentaspagar",
            name="indice_gestion_cloro",
        ),
        migrations.AddField(
            model_name="cuentaspagar",
            name="ciclo_pagos_dias",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ciclo de Cobros (Días)",
            ),
        ),
        migrations.AddField(
            model_name="cuentaspagar",
            name="efectos_por_pagar",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Efectos Por Pagar",
            ),
        ),
        migrations.AddField(
            model_name="cuentaspagar",
            name="indice_gestion_pago",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Índice Gestión Pago",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="diferencia_incio_anno",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diferencia con Inicio de Año",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="diferencia_mes_anterior",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diferencia con Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="inicio_anno",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inicio de Año",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_actual",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Mes Actual",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_actual_vencidas",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas Mes Actual",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_anterior",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="mes_anterior_vencidas",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaspagar",
            name="saldo_al_inicio",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Saldo al Inicio",
            ),
        ),
    ]
