# Generated by Django 4.2.7 on 2025-04-03 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_remove_cuentaspagar_ciclo_cobros_dias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentascobrar",
            name="por_cobrar_a_terceros",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Por Cobrar: a Terceros",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="por_cobrar_grupo",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Por Cobrar: Grupo",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="por_cobrar_total",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Por Cobrar: Total",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="por_cobrar_u_admin",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Por Cobrar: Unidad Adminstrativa",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="porcentage_a_terceros",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="%: a Terceros",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="porcentage_grupo",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="%: Grupo",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="porcentage_total",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="%: Total",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="porcentage_u_admin",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="%: Unidad Adminstrativa",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="vencidas_a_terceros",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas: a Terceros",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="vencidas_grupo",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas: Grupo",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="vencidas_total",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas: Total",
            ),
        ),
        migrations.AddField(
            model_name="cuentascobrar",
            name="vencidas_u_admin",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas: Unidad Adminstrativa",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="ciclo_cobros_dias",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ciclo de Cobros (Días)",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="diferencia_incio_anno",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diferencia con Inicio de Año",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="diferencia_mes_anterior",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diferencia con Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="indice_gestion_cloro",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Índice Gestión Cloro",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="inicio_anno",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inicio de Año",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_actual",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Mes Actual",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_actual_vencidas",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas Mes Actual",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_anterior",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="mes_anterior_vencidas",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Vencidas Mes Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="cuentascobrar",
            name="saldo_al_inicio",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Saldo al Inicio",
            ),
        ),
    ]
