# Generated by Django 4.2.7 on 2025-04-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_remove_cuentascobrar_indice_gestion_cloro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoberaniaAlimentaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(max_length=50, verbose_name="Unidad"),
                ),
                (
                    "huertos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Huertos"
                    ),
                ),
                (
                    "canteros",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Canteros"
                    ),
                ),
                (
                    "tierras",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tierras"
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soberanía Alimentaria",
                "verbose_name_plural": "Soberanias Alimentarias",
            },
        ),
    ]
