# Generated by Django 4.2.7 on 2025-04-05 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0018_perfeccionamientocomerciogastronomia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="porciento",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_no_nominales",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Inversiones no nominales: Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_obra",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Preparación de obra: Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_resto",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Resto de inversiones no nominales: Porcentaje",
            ),
        ),
        migrations.CreateModel(
            name="Perdida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.PositiveIntegerField(verbose_name="Plan")),
                ("real", models.PositiveIntegerField(verbose_name="Real")),
                (
                    "porciento",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        max_length=256, verbose_name="Indicadores"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perdida",
                "verbose_name_plural": "Perdidas",
                "unique_together": {("empresa", "indicador")},
            },
        ),
    ]
