# Generated by Django 4.2.7 on 2025-04-05 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_alter_indicadorgeneral_porciento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perdida",
            name="indicador",
            field=models.CharField(max_length=256, verbose_name="Indicador"),
        ),
        migrations.CreateModel(
            name="TransportacionDePasajeros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aprobadas",
                    models.PositiveIntegerField(verbose_name="Aprobadas"),
                ),
                (
                    "real_ejecutadas",
                    models.PositiveIntegerField(verbose_name="Real Ejecutadas"),
                ),
                (
                    "porciento",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(max_length=256, verbose_name="Indicador"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportación de Pasajeros",
                "verbose_name_plural": "Transportaciones de Pasajeros",
                "unique_together": {("empresa", "indicador")},
            },
        ),
    ]
