# Generated by Django 4.2.7 on 2025-04-05 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0021_transportaciondecarga"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.PositiveIntegerField(verbose_name="Plan")),
                (
                    "en_falta",
                    models.PositiveIntegerField(verbose_name="En Falta"),
                ),
                (
                    "porciento_de_afectacion",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de Afectación",
                    ),
                ),
                (
                    "medicamento",
                    models.CharField(
                        max_length=256, verbose_name="Medicamento"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "unique_together": {("empresa", "medicamento")},
            },
        ),
    ]
