# Generated by Django 4.2.7 on 2025-04-05 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_medicamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicadorgeneral",
            name="porciento",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_no_nominales",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Inversiones no nominales: Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_obra",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Preparación de obra: Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="inversiones",
            name="porciento_resto",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Resto de inversiones no nominales: Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="porciento_de_afectacion",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje de Afectación",
            ),
        ),
        migrations.AlterField(
            model_name="perdida",
            name="porciento",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="transportaciondecarga",
            name="porciento",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="transportaciondepasajeros",
            name="porciento",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
    ]
