# Generated by Django 4.2.7 on 2025-04-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_informaciongeneral"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanDeConstruccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.PositiveIntegerField(verbose_name="Plan")),
                ("real", models.PositiveIntegerField(verbose_name="Real")),
                (
                    "donde_se_incumple",
                    models.TextField(verbose_name="Donde se Incumple"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=256, verbose_name="Nombre Del Plan"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Construcción",
                "verbose_name_plural": "Planes de Construcción",
                "unique_together": {("empresa", "nombre")},
            },
        ),
    ]
