# Generated by Django 4.2.7 on 2025-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0025_plandeconstruccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandeconstruccion",
            name="donde_se_incumple",
            field=models.TextField(
                blank=True, null=True, verbose_name="Donde se Incumple"
            ),
        ),
    ]
