# Generated by Django 4.2.7 on 2025-04-10 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0027_indicadorgeneralgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiculosCumnales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Camion", "Camion"),
                            ("Tractores", "Tractores"),
                            ("Camion Especializados", "Camion Especializados"),
                            ("Camion Ampliroel", "Camion Ampliroel"),
                            ("Buldocer", "Buldocer"),
                            ("Cargador Frontal", "Cargador Frontal"),
                        ],
                        max_length=256,
                        verbose_name="Vehiculo",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(verbose_name="Camiones"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=256, verbose_name="Vehiculo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comunales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.PositiveIntegerField(verbose_name="Plan")),
                ("real", models.PositiveIntegerField(verbose_name="Real")),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vehiculos",
                    models.ManyToManyField(
                        to="project.vehiculoscumnales", verbose_name="Vehiculos"
                    ),
                ),
            ],
        ),
    ]
