# Generated by Django 4.2.7 on 2025-04-17 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0029_vehiculoscumnales_activo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comunales",
            options={
                "verbose_name": "Comunales",
                "verbose_name_plural": "Comunales",
            },
        ),
        migrations.AlterModelOptions(
            name="indicadorgeneral",
            options={
                "verbose_name": "Pérdida Alimentaria",
                "verbose_name_plural": "Perdidas Alimentarias",
            },
        ),
        migrations.AlterModelOptions(
            name="informaciongeneral",
            options={
                "verbose_name": "Seguridad y Protección",
                "verbose_name_plural": "Seguridad y Protección",
            },
        ),
        migrations.AlterModelOptions(
            name="perdida",
            options={
                "verbose_name": "Perdida Farmacia",
                "verbose_name_plural": "Perdidas Farmacia",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiculoscumnales",
            options={
                "verbose_name": "Vehiculo Cumnales",
                "verbose_name_plural": "Vehiculos Cumnales",
            },
        ),
        migrations.RemoveField(
            model_name="indicadorgeneral",
            name="porciento",
        ),
    ]
