# Generated by Django 4.2.7 on 2025-04-17 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0030_alter_comunales_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inversiones",
            name="empresa",
        ),
    ]
