# Generated by Django 4.2.7 on 2025-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0031_remove_inversiones_empresa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="atencionalafamilia",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="atencionalafamilia",
            name="fecha",
            field=models.DateField(unique=True, verbose_name="Fecha"),
        ),
        migrations.RemoveField(
            model_name="atencionalafamilia",
            name="empresa",
        ),
    ]
