# Generated by Django 4.2.7 on 2025-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0032_alter_atencionalafamilia_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="perfeccionamientocomerciogastronomia",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="perfeccionamientocomerciogastronomia",
            name="anno",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Año al que corresponden los datos",
                unique=True,
                verbose_name="Año",
            ),
        ),
        migrations.RemoveField(
            model_name="perfeccionamientocomerciogastronomia",
            name="empresa",
        ),
    ]
