# Generated by Django 4.2.7 on 2025-04-17 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0033_alter_perfeccionamientocomerciogastronomia_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plandeconstruccion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="plandeconstruccion",
            name="empresa",
        ),
    ]
