# Generated by Django 4.2.7 on 2025-04-17 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0035_alter_informaciongeneral_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transportaciondepasajeros",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="transportaciondepasajeros",
            name="empresa",
        ),
    ]
