# Generated by Django 4.2.7 on 2025-04-17 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0036_alter_transportaciondepasajeros_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comunales",
            name="empresa",
        ),
    ]
