# Generated by Django 4.2.7 on 2025-04-18 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0037_remove_comunales_empresa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="perdida",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="perdida",
            name="empresa",
        ),
    ]
