# Generated by Django 4.2.7 on 2025-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0039_alter_inmuebles_almacenes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicadorgeneral",
            options={
                "verbose_name": "Pérdida Alimentaria",
                "verbose_name_plural": "Pérdidas Alimentarias",
            },
        ),
        migrations.AlterModelOptions(
            name="perdida",
            options={
                "verbose_name": "Pérdida Farmacia",
                "verbose_name_plural": "Pérdidas Farmacia",
            },
        ),
        migrations.AlterModelOptions(
            name="soberaniaalimentaria",
            options={
                "verbose_name": "Soberanía Alimentaria",
                "verbose_name_plural": "Soberanías Alimentarias",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiculoscumnales",
            options={
                "verbose_name": "Vehículo Comunales",
                "verbose_name_plural": "Vehículos Comunales",
            },
        ),
        migrations.RemoveField(
            model_name="indicadorgeneral",
            name="empresa",
        ),
        migrations.AlterField(
            model_name="comunales",
            name="vehiculos",
            field=models.ManyToManyField(
                to="project.vehiculoscumnales", verbose_name="Vehículos"
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="municipio",
            field=models.CharField(
                choices=[
                    ("San Jose", "San José de las Lajas"),
                    ("Batabano", "Batabanó"),
                    ("Bejucal", "Bejucal"),
                    ("San Nicolas de Bari", "San Nicolás de Bari"),
                    ("Guines", "Güines"),
                    ("Jaruco", "Jaruco"),
                    ("Madruga", "Madruga"),
                    ("Melena", "Melena del Sur"),
                    ("Nueva Paz", "Nueva Paz"),
                    ("Santa Cruz", "Santa Cruz del Norte"),
                    ("Quivican", "Quivicán"),
                ],
                max_length=50,
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="delitos",
            name="tipocidad",
            field=models.CharField(
                choices=[
                    ("Robo con fuerza", "Robo con Fuerza"),
                    ("Hurto", "Hurto"),
                    ("Malversacion", "Malversación"),
                ],
                max_length=50,
                verbose_name="Tipicidad",
            ),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="fabricas",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="fábricas"
            ),
        ),
        migrations.AlterField(
            model_name="inmuebles",
            name="farmacias_opticas",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="farmacias y ópticas / C. auditivo",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculoscumnales",
            name="municipio",
            field=models.CharField(
                choices=[
                    ("San Jose", "San José de las Lajas"),
                    ("Batabano", "Batabanó"),
                    ("Bejucal", "Bejucal"),
                    ("San Nicolas de Bari", "San Nicolás de Bari"),
                    ("Guines", "Güines"),
                    ("Jaruco", "Jaruco"),
                    ("Madruga", "Madruga"),
                    ("Melena", "Melena del Sur"),
                    ("Nueva Paz", "Nueva Paz"),
                    ("Santa Cruz", "Santa Cruz del Norte"),
                    ("Quivican", "Quivicán"),
                ],
                max_length=256,
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculoscumnales",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Camión", "Camión"),
                    ("Tractores", "Tractores"),
                    ("Camión Especializado", "Camión Especializado"),
                    ("Camión Ampliroel", "Camión Ampliroel"),
                    ("Buldocer", "Buldocer"),
                    ("Cargador Frontal", "Cargador Frontal"),
                ],
                max_length=256,
                verbose_name="Vehículo",
            ),
        ),
    ]
