# Generated by Django 4.2.7 on 2025-04-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_alter_indicadorgeneral_options_alter_perdida_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionalafamilia',
            name='total_beneficiarios',
        ),
    ]
