# Generated by Django 4.2.7 on 2025-04-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_remove_atencionalafamilia_total_beneficiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversiones',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
