# Generated by Django 4.2.7 on 2025-04-24 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0042_inversiones_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delitos",
            name="denuncia",
        ),
        migrations.AlterField(
            model_name="delitos",
            name="no_denuncia",
            field=models.IntegerField(
                max_length=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="No. Denuncia",
            ),
        ),
    ]
